In [34]:
import numpy as np

a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [35]:
# Package imports
import time
import matplotlib.pyplot as plt
import sklearn
import sklearn.datasets
import sklearn.linear_model
b = np.random.rand(100000000)
c = np.random.rand(100000000)
d = np.dot(b,c)
print(d)

24999168.404


In [36]:
u = np.exp(a)
print(u)

[   2.71828183    7.3890561    20.08553692   54.59815003  148.4131591 ]


In [37]:
a.T

array([1, 2, 3, 4, 5])

In [38]:
a

array([1, 2, 3, 4, 5])

In [39]:
a + a.T

array([ 2,  4,  6,  8, 10])

In [40]:
a = np.random.rand(3,3)
b = np.random.rand(3, 1)
c = a*b
print(c)

[[ 0.08288448  0.04664505  0.03674973]
 [ 0.09469046  0.29463165  0.09549865]
 [ 0.05163759  0.02308693  0.08073217]]


In [41]:
A = np.random.rand(4,3)
B = np.sum(A, axis=1,keepdims=True)
B.shape

(4, 1)

In [42]:
a = range(1, 10)

In [43]:
a[0]

1

In [44]:
caches = []

In [45]:
caches

[]

In [46]:
caches.insert(2, a)

In [47]:
caches

[[1, 2, 3, 4, 5, 6, 7, 8, 9]]

In [48]:
reversed(range(10-1))

In [49]:
reversed(range(9))

In [50]:
p = 0.8

In [51]:
range(1, 11)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [52]:
b = {}
layers_dims = [2,3,3,1]

In [53]:
b['w' + str(2)] = np.zeros((layers_dims[2], layers_dims[1]))

In [54]:
b['w2']

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [55]:
import tensorflow as tf

In [56]:
y_hat = tf.constant(36, name='y_hat')            # Define y_hat constant. Set to 36.
y = tf.constant(39, name='y')                    # Define y. Set to 39

loss = tf.Variable((y - y_hat)**2, name='loss')  # Create a variable for the loss

init = tf.global_variables_initializer()         # When init is run later (session.run(init)),
                                                 # the loss variable will be initialized and ready to be computed
with tf.Session() as session:                    # Create a session and print the output
    session.run(init)                            # Initializes the variables
    print(session.run(loss)) 

9
